version: '3.8'

services:
  synthetic-data-generator:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./responses:/app/responses
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - ENVIRONMENT=production
    restart: unless-stopped